development:
  adapter: postgresql
  encoding: unicode
  database: smiles
  pool: 5
  username: postgres
  password: Pa$$w0rd
test:
  adapter: postgresql
  encoding: unicode
  database: smiles
  pool: 5
  username: postgres
  password: Pa$$w0rd
production:
  adapter: postgresql
  encoding: unicode
  database: smiles
  pool: 5
  username: postgres
  password: Pa$$w0rd
